# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: refresh.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "refresh.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rrefresh.proto\x12\x07refresh"0\n\x0eRefreshRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t"\x11\n\x0fRefreshResponse2S\n\x0eRefreshService\x12\x41\n\x0cRefreshToken\x12\x17.refresh.RefreshRequest\x1a\x18.refresh.RefreshResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "refresh_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_REFRESHREQUEST"]._serialized_start = 26
    _globals["_REFRESHREQUEST"]._serialized_end = 74
    _globals["_REFRESHRESPONSE"]._serialized_start = 76
    _globals["_REFRESHRESPONSE"]._serialized_end = 93
    _globals["_REFRESHSERVICE"]._serialized_start = 95
    _globals["_REFRESHSERVICE"]._serialized_end = 178
# @@protoc_insertion_point(module_scope)
